# Generated by Django 2.0.7 on 2018-07-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('avatar', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('authentications', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
    ]
