# Generated by Django 2.0.7 on 2018-07-13 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryNum', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagNum', models.IntegerField(primary_key=True, serialize=False)),
                ('tagName', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Category')),
            ],
        ),
    ]
