# Generated by Django 2.0.7 on 2018-07-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_category_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('followNum', models.AutoField(primary_key=True, serialize=False)),
                ('followTagName', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('labelNum', models.AutoField(primary_key=True, serialize=False)),
                ('labelDes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureNum', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postNum', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('postDes', models.TextField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceNum', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.TextField()),
                ('serviceDes', models.TextField()),
                ('price', models.IntegerField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagNum',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Post'),
        ),
        migrations.AddField(
            model_name='label',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Tag'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User'),
        ),
    ]
