# Generated by Django 2.0.7 on 2018-07-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20180713_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryId',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='labelName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
