# Generated by Django 2.0.7 on 2018-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20180714_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_des',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
