# Generated by Django 2.0.7 on 2018-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_user_user_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.TimeField(),
        ),
    ]
