# Generated by Django 2.0.7 on 2018-07-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20180716_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePicture',
            fields=[
                ('pictureNum', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Service')),
            ],
        ),
        migrations.RenameModel(
            old_name='Picture',
            new_name='PostPicture',
        ),
    ]
