# Generated by Django 2.0.7 on 2018-07-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20180718_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceDetail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
