# Generated by Django 2.0.7 on 2018-07-19 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20180718_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentType', models.BooleanField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('createTime', models.DateTimeField()),
                ('serviceTime', models.DateTimeField()),
                ('completeTime', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Order'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User'),
        ),
    ]
