# Generated by Django 2.0.7 on 2018-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_auto_20180719_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
