# Generated by Django 2.0.7 on 2018-07-19 13:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20180719_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 19, 21, 16, 10, 637720)),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
