# Generated by Django 2.0.7 on 2018-07-21 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20180719_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagSearchNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 21, 11, 0, 7, 371294)),
        ),
    ]
